# Generated by Django 2.0.1 on 2018-05-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_categoru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categoru',
            new_name='category',
        ),
    ]
